framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            failed: 'doctrine://default?queue_name=failed&auto_setup=0'

            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            async-contact:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                    queue_name: async-contact
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                failure_transport: async-contact-failed
            async-pdf:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                    queue_name: async-pdf
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
                failure_transport: async-pdf-failed

            async-contact-failed: 'doctrine://default?queue_name=async-contact-failed&auto_setup=0'
            async-pdf-failed: 'doctrine://default?queue_name=async-pdf-failed&auto_setup=0'
        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async-contact
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            'App\Message\RecipePDFMessage': async-pdf

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
