scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    google:
        enabled: true
        server_name: Recipes
        issuer: Recipes
        digits: 6
        leeway: 5
        template: security/2fa_form.html.twig
